-- ════════════════════════════════════════════════════════════════════
-- Migration 008: Seed the product catalog with real NZ solar inventory
-- Safe to re-run — uses ON CONFLICT (sku) DO NOTHING.
-- ════════════════════════════════════════════════════════════════════

INSERT INTO products (sku, name, brand, category, model, description, price, compare_price, price_unit, image_url, specs, stock_qty, is_featured) VALUES

-- ── SOLAR PANELS ──
('REC-ALPHA-PURE-R-430', 'REC Alpha Pure-R 430W Panel',     'REC',              'panel',     'Alpha Pure-R 430W',  'Premium N-type heterojunction panel. 22.3% efficiency — the highest on the NZ market. Excellent low-light performance ideal for cloudy NZ conditions.',                              399.00, 449.00, 'per panel', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"430W","efficiency":"22.3%","warranty_product":"25 years","warranty_performance":"25 years","cell_type":"HJT","dimensions":"1730 x 1118 x 30mm","country":"Norway"}'::jsonb, 400, true),
('JINKO-TIGER-NEO-440',   'Jinko Tiger Neo N-Type 440W',      'Jinko Solar',      'panel',     'Tiger Neo 440W',     'World #1 panel maker. N-type TOPCon cells deliver excellent bifacial gain for commercial rooftop installations.',                                                                     219.00, 249.00, 'per panel', 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"440W","efficiency":"22.3%","warranty_product":"12 years","warranty_performance":"25 years","cell_type":"N-type TOPCon","country":"China"}'::jsonb, 850, true),
('LONGI-HIMO6-435',       'LONGi Hi-MO 6 435W',              'LONGi Solar',      'panel',     'Hi-MO 6 435W',       'Industry-leading cell efficiency with a 30-year linear performance warranty (highest available in NZ).',                                                                               239.00, 289.00, 'per panel', 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"435W","efficiency":"22.3%","warranty_product":"15 years","warranty_performance":"30 years","cell_type":"HPBC","country":"China"}'::jsonb, 500, false),
('CS-HIKU6-415',          'Canadian Solar HiKu6 415W',        'Canadian Solar',   'panel',     'HiKu6 Mono PERC',    'NYSE-listed manufacturer with strong financials — a safe bet for long-term warranty enforcement.',                                                                                    189.00, 219.00, 'per panel', 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"415W","efficiency":"21.3%","warranty_product":"12 years","warranty_performance":"25 years","cell_type":"Mono PERC","country":"Canada"}'::jsonb, 720, false),
('PHONO-DRACO-M10-410',   'Phono Draco M10 410W',             'Phono Solar',      'panel',     'Draco M10 410W',     'Top-10 Chinese manufacturer. Excellent price-to-performance for mid-market residential installs.',                                                                                    175.00, 195.00, 'per panel', 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"410W","efficiency":"21.0%","warranty_product":"15 years","warranty_performance":"25 years","cell_type":"Mono PERC","country":"China"}'::jsonb, 1200, false),
('TRINA-VERTEX-445',      'Trina Vertex S+ 445W',             'Trina Solar',      'panel',     'Vertex S+ 445W',     'Large 210mm wafer technology. Vertex series drives utility-scale PV globally.',                                                                                                        209.00, 239.00, 'per panel', 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=600&h=480&fit=crop&auto=format&q=80',  '{"wattage":"445W","efficiency":"22.0%","warranty_product":"12 years","warranty_performance":"25 years","cell_type":"Mono PERC","country":"China"}'::jsonb, 650, false),

-- ── INVERTERS ──
('FRONIUS-PRIMO-GEN24-6', 'Fronius Primo GEN24 Plus 6.0 kW',   'Fronius',          'inverter',  'Primo GEN24 Plus 6.0', 'Austrian-built hybrid inverter. Works with any battery and any retailer. Whisper-quiet, Wi-Fi built in.',                                                                              3590.00, 3890.00, 'each', 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"6.0kW","max_pv":"9kW","phases":"single","warranty":"10 years","hybrid":true,"country":"Austria"}'::jsonb, 45, true),
('FRONIUS-SYMO-GEN24-10', 'Fronius Symo GEN24 Plus 10 kW',     'Fronius',          'inverter',  'Symo GEN24 Plus 10', '3-phase hybrid inverter for larger residential + light commercial. Supports battery backup.',                                                                                          5490.00, 5990.00, 'each', 'https://images.unsplash.com/photo-1620714223084-8fcacc6dfd8d?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"10kW","max_pv":"15kW","phases":"three","warranty":"10 years","hybrid":true,"country":"Austria"}'::jsonb, 18, false),
('SUNGROW-SG5-0RS',       'Sungrow SG5.0RS',                    'Sungrow',          'inverter',  'SG5.0RS',            'Global bestseller by volume. 98.4% efficiency, built-in arc fault detection, 10-year warranty.',                                                                                       1990.00, 2290.00, 'each', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"5.0kW","max_pv":"7.5kW","phases":"single","warranty":"10 years","hybrid":false,"country":"China"}'::jsonb, 60, false),
('SUNGROW-SH10RT',        'Sungrow SH10RT Hybrid',              'Sungrow',          'inverter',  'SH10RT Hybrid',      '3-phase hybrid, works beautifully with Sungrow battery. Backup output for essential circuits.',                                                                                        4290.00, 4690.00, 'each', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"10kW","max_pv":"15kW","phases":"three","warranty":"10 years","hybrid":true,"country":"China"}'::jsonb, 22, false),
('ENPHASE-IQ8M',          'Enphase IQ8M Microinverter',         'Enphase',          'inverter',  'IQ8M',               'Per-panel microinverter. 25-year warranty. Handles partial shading brilliantly.',                                                                                                      335.00, 379.00, 'per panel', 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"330 VA","warranty":"25 years","per_panel":true,"rapid_shutdown":true,"country":"USA"}'::jsonb, 180, false),
('SMA-SUNNYBOY-5',        'SMA Sunny Boy 5.0',                  'SMA',              'inverter',  'Sunny Boy 5.0',      'German-engineered 20-year track record in NZ. Unmatched service history.',                                                                                                             2590.00, 2890.00, 'each', 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"5.0kW","max_pv":"7.5kW","phases":"single","warranty":"10 years","country":"Germany"}'::jsonb, 35, false),

-- ── BATTERIES ──
('TESLA-POWERWALL-3',     'Tesla Powerwall 3',                  'Tesla',            'battery',   'Powerwall 3',        'The most popular home battery globally. Integrated hybrid inverter (no extra inverter needed for battery-only upgrade).',                                                              16990.00, 17990.00, 'each', 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=600&h=480&fit=crop&auto=format&q=80',  '{"capacity":"13.5 kWh","peak_power":"11.5 kW","warranty":"10 years · 70% capacity","chemistry":"LFP","backup":true,"country":"USA"}'::jsonb, 12, true),
('BYD-HVS-10-2',          'BYD Battery-Box Premium HVS 10.2 kWh','BYD',             'battery',   'Battery-Box HVS 10.2', 'Modular stacking from 5 to 22 kWh. Works with Fronius, Sungrow, SMA, Victron.',                                                                                                        11490.00, 12490.00, 'each', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=480&fit=crop&auto=format&q=80',  '{"capacity":"10.2 kWh","warranty":"10 years · 60% capacity","chemistry":"LFP","modular":true,"country":"China"}'::jsonb, 20, false),
('SONNEN-EVO-10',         'sonnenBatterie Evo 10',              'sonnen',           'battery',   'sonnenBatterie Evo 10','Premium German LFP chemistry with longest cycle-life guarantee (10,000 cycles).',                                                                                                      14990.00, 15990.00, 'each', 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600&h=480&fit=crop&auto=format&q=80',  '{"capacity":"10 kWh","warranty":"10 years · 10,000 cycles","chemistry":"LFP","country":"Germany"}'::jsonb, 8, false),
('FREEDOMWON-ETOWER-5',   'Freedom Won eTower 5 kWh',           'Freedom Won',      'battery',   'eTower 5',           'Off-grid LFP workhorse. Massive capacity options make these the go-to for farms and lodges.',                                                                                          5490.00, 5990.00, 'each', 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&h=480&fit=crop&auto=format&q=80',  '{"capacity":"5 kWh","warranty":"10 years · 80% capacity","chemistry":"LFP","country":"South Africa"}'::jsonb, 40, false),
('ENPHASE-IQ-BATT-5P',    'Enphase IQ Battery 5P',              'Enphase',          'battery',   'IQ Battery 5P',      'AC-coupled 5 kWh modular battery with built-in microinverter. Perfect for retrofits.',                                                                                                8490.00, 8990.00, 'each', 'https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=600&h=480&fit=crop&auto=format&q=80',  '{"capacity":"5 kWh","warranty":"15 years","chemistry":"LFP","ac_coupled":true,"country":"USA"}'::jsonb, 25, false),

-- ── EV CHARGERS ──
('ZAPPI-V21-7',           'Zappi v2.1 7kW EV Charger',          'myenergi',         'ev_charger','Zappi v2.1 7kW',     'Solar-diverting EV charger. Routes 100% of excess solar to your car instead of exporting at 10c/kWh buy-back.',                                                                        1890.00, 2190.00, 'each', 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"7.4 kW","phase":"single","solar_aware":true,"warranty":"3 years","country":"UK"}'::jsonb, 30, true),
('WALLBOX-PULSAR-22',     'Wallbox Pulsar Max 22kW',            'Wallbox',          'ev_charger','Pulsar Max 22kW',    'Smallest 22kW charger on the market. Phone-app scheduling, OCPP 1.6.',                                                                                                                 1690.00, 1890.00, 'each', 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"22 kW","phase":"three","warranty":"3 years","country":"Spain"}'::jsonb, 22, false),
('FRONIUS-WATTPILOT-22',  'Fronius Wattpilot Home 22 J',        'Fronius',          'ev_charger','Wattpilot Home 22 J','Pairs natively with Fronius inverters for solar-surplus charging without extra hardware.',                                                                                            1590.00, 1790.00, 'each', 'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=600&h=480&fit=crop&auto=format&q=80',  '{"power":"22 kW","phase":"three","solar_aware":true,"warranty":"2 years","country":"Austria"}'::jsonb, 18, false),

-- ── MOUNTING ──
('S5-PVKIT-2',            'S-5! PVKIT 2.0 (per panel)',          'S-5!',             'mounting',  'PVKIT 2.0',          'Non-penetrating clamp kit for standing-seam and corrugated metal roofs. Preserves roof warranty.',                                                                                     49.00, 59.00, 'per panel', 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Metal roof clamp","warranty":"Lifetime","country":"USA"}'::jsonb, 900, false),
('SUNLOCK-TILE',          'Sunlock T-Series Tile Hook',         'Sunlock',          'mounting',  'T-Series Tile Hook', 'Australian-engineered for southern-hemisphere wind zones. Pre-assembled rails cut install time 30%.',                                                                                29.00, 35.00, 'each',      'https://images.unsplash.com/photo-1497440001374-f26997328c1b?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Tile roof hook","warranty":"10 years","country":"Australia"}'::jsonb, 1500, false),
('SCHLETTER-FS-UNO',      'Schletter FS Uno Ground-Mount Rail', 'Schletter',        'mounting',  'FS Uno',             'German-engineered aluminium substructure for commercial ground-mount up to 1 MW arrays.',                                                                                             89.00, 99.00, 'per metre', 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Ground mount rail","warranty":"15 years","country":"Germany"}'::jsonb, 600, false),

-- ── MONITORING ──
('TIGO-TS4-A-O',          'Tigo TS4-A-O Optimiser',             'Tigo',             'monitoring','TS4-A-O',            'Panel-level optimiser for string inverters. Mitigates shading and provides per-panel telemetry.',                                                                                     89.00, 99.00, 'per panel', 'https://images.unsplash.com/photo-1611365892117-00ac5ef43c90?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Panel optimiser","warranty":"25 years","country":"USA"}'::jsonb, 350, false),
('ENPHASE-IQ-GATEWAY',    'Enphase IQ Gateway Metered',         'Enphase',          'monitoring','IQ Gateway',         'Real-time per-panel telemetry via phone app, cellular or Wi-Fi. Standard with every Enphase system.',                                                                                  990.00, 1190.00, 'each', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Monitoring gateway","warranty":"5 years","country":"USA"}'::jsonb, 50, false),
('SOLAR-ANALYTICS-MON',   'Solar Analytics SA Monitor',         'Solar Analytics',  'monitoring','SA Monitor',         'Independent brand-agnostic monitoring. 5-minute granularity + plan-switching + tariff advice.',                                                                                       499.00, 599.00, 'each',      'https://images.unsplash.com/photo-1559302504-64aae6ca6b6d?w=600&h=480&fit=crop&auto=format&q=80',  '{"type":"Smart monitor","subscription":"from $9.90/mo","country":"Australia"}'::jsonb, 80, false)

ON CONFLICT (sku) DO NOTHING;
